export const locations = [
  "Windhoek Central",
  "Khomasdal",
  "Katutura",
  "Eros",
  "Klein Windhoek",
  "Pioneers Park",
  "Academia",
  "Olympia",
  "Hochland Park",
  "Kleine Kuppe",
  "Dorado Park",
  "Otjomuise",
  "Cimbebasia",
  "Rocky Crest",
  "Wanaheda",
  "Goreangab",
  "Elisenheim",
];

export const futureLocations = [
  "Swakopmund",
  "Walvis Bay",
  "Henties Bay",
  "Oshakati",
  "Ongwediva",
  "Rundu",
  "Keetmanshoop",
  "Rehoboth",
  "Gobabis",
  "Tsumeb",
  "Otjiwarongo",
];

export const propertyTypes = [
  "Room",
  "Shared room",
  "Bachelor flat",
  "Apartment",
  "Flat",
  "Townhouse",
  "House",
  "Student accommodation",
  "Backyard flat",
  "Short-term rental",
  "Guest suite",
  "Holiday apartment",
];

export const priceRanges = [
  { label: "Below N$2,000", min: "", max: "2000" },
  { label: "N$2,000 - N$3,500", min: "2000", max: "3500" },
  { label: "N$3,500 - N$5,000", min: "3500", max: "5000" },
  { label: "N$5,000 - N$8,000", min: "5000", max: "8000" },
  { label: "N$8,000 - N$12,000", min: "8000", max: "12000" },
  { label: "Above N$12,000", min: "12000", max: "" },
];

export const listings = [
  {
    id: "facebook-wanaheda-inside-room",
    title: "Inside Room in Wanaheda",
    description:
      "Imported from a Facebook group post. Inside room in Wanaheda with hot water, shared kitchen and bathroom, boundary wall, and no deposit mentioned.",
    price: 1800,
    deposit: 0,
    location: "Wanaheda",
    city: "Windhoek",
    propertyType: "Room",
    category: "Affordable rentals",
    bedrooms: "Single room",
    bathrooms: 1,
    parking: 0,
    furnished: "Unspecified",
    utilities: "Hot water mentioned; confirm utilities with advertiser",
    availableFrom: "Month end",
    pricePeriod: "per month",
    badges: ["Facebook Import", "No Deposit Mentioned", "Affordable"],
    image: "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Facebook Group Import", phone: "Verify on Facebook", whatsapp: "264000000000", email: "imports@namrent.na" },
    features: ["Shared kitchen", "Shared bathroom", "Hot water", "Boundary wall"],
    safety: "Imported from Facebook MHTML. Verify advertiser identity, location, availability, and payment terms before paying.",
    status: "active",
    isFeatured: true,
    popularity: 72,
  },
  {
    id: "facebook-khomasdal-one-bedroom-flat",
    title: "1 Bedroom Flat in Khomasdal",
    description:
      "Imported from a Facebook group post. One bedroom flat in a safe complex in Khomasdal, with utilities mentioned as included. The source text had conflicting price snippets, so confirm price directly.",
    price: 6000,
    deposit: 0,
    location: "Khomasdal",
    city: "Windhoek",
    propertyType: "Flat",
    category: "Affordable rentals",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    furnished: "Unspecified",
    utilities: "Utilities mentioned as included",
    availableFrom: "Confirm with advertiser",
    pricePeriod: "per month",
    badges: ["Facebook Import", "Utilities Included", "Verify Price"],
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Facebook Group Import", phone: "Verify on Facebook", whatsapp: "264000000000", email: "imports@namrent.na" },
    features: ["Safe complex mentioned", "Utilities included", "Khomasdal area", "Imported listing"],
    safety: "Imported from Facebook MHTML. The source included conflicting N$4,500/N$6,000 price snippets; confirm before arranging payment.",
    status: "active",
    isFeatured: true,
    popularity: 74,
  },
  {
    id: "villa-verdi-student-residence",
    title: "Villa Verdi Student Residence",
    description:
      "Female student residence in Windhoek West with shared and single rooms, study spaces, laundry, recreation areas, netball court, and indoor gym.",
    price: 3750,
    deposit: 3750,
    location: "Windhoek West",
    city: "Windhoek",
    propertyType: "Student accommodation",
    category: "Student rentals",
    bedrooms: "Shared or single rooms",
    bathrooms: 1,
    parking: 0,
    furnished: "Furnished",
    utilities: "Utilities and amenities vary by room option",
    availableFrom: "Waiting list available",
    pricePeriod: "per month",
    badges: ["Female Residence", "Study Centre", "Indoor Gym"],
    roomOptions: [
      { name: "Shared Room", price: 3750, image: "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5178-scaled.jpg" },
      { name: "Single Room", price: 5150, image: "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5186-scaled.jpg" },
      { name: "Study Residence", price: 5150, image: "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5198-scaled.jpg" },
    ],
    image: "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5178-scaled.jpg",
    gallery: [
      "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5178-scaled.jpg",
      "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5186-scaled.jpg",
      "https://studentstay.com.na/wp-content/uploads/2025/12/DSCF5198-scaled.jpg",
    ],
    contact: { name: "Student Stay", phone: "+264 81 555 0101", whatsapp: "264815550101", email: "students@namrent.na" },
    features: ["Study spaces", "Laundry", "Recreation areas", "Netball court", "Indoor gym"],
    safety: "Confirm current availability, room rules, and payment instructions directly with the residence provider.",
    status: "active",
    isFeatured: true,
    popularity: 96,
  },
  {
    id: "mercury-house-student-residence",
    title: "Mercury House Student Residence",
    description:
      "Student accommodation option connected to Student Stay, suitable for students looking for organised residence living in Windhoek.",
    price: 3500,
    deposit: 3500,
    location: "Windhoek West",
    city: "Windhoek",
    propertyType: "Student accommodation",
    category: "Student rentals",
    bedrooms: "Student rooms",
    bathrooms: 1,
    parking: 0,
    furnished: "Furnished",
    utilities: "Confirm utilities with provider",
    availableFrom: "Confirm with provider",
    pricePeriod: "per month",
    badges: ["Student Residence", "Windhoek West", "Managed Accommodation"],
    roomOptions: [
      { name: "Student Room", price: 3500, image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80" },
      { name: "Shared Room", price: 3300, image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80" },
      { name: "Single Room", price: 4200, image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80" },
    ],
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Student Stay", phone: "+264 81 555 0102", whatsapp: "264815550102", email: "mercury@namrent.na" },
    features: ["Student-focused accommodation", "Managed residence", "Shared facilities", "Application link available"],
    safety: "Confirm Mercury House room prices, rules, and availability with the provider before paying.",
    status: "active",
    isFeatured: true,
    popularity: 92,
  },
  {
    id: "capital-residence-student-accommodation",
    title: "Capital Residence Student Accommodation",
    description:
      "Central Windhoek student accommodation with single, twin, triple, and quad room options for up to 400 residents.",
    price: 2798,
    deposit: 2798,
    location: "Windhoek Central",
    city: "Windhoek",
    propertyType: "Student accommodation",
    category: "Student rentals",
    bedrooms: "Single, twin, triple or quad",
    bathrooms: 1,
    parking: 0,
    furnished: "Partially furnished",
    utilities: "Limited Wi-Fi and residence services included",
    availableFrom: "Applications open",
    pricePeriod: "per month",
    badges: ["CBD Location", "Biometric Access", "Cleaning"],
    roomOptions: [
      { name: "Quad Room", price: 2798, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9872-min-1024x683.jpg" },
      { name: "Single Room", price: 4310, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9864-min-1024x683.jpg" },
      { name: "Twin Room", price: 2950, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9882-min-1024x683.jpg" },
      { name: "Triple Room", price: 2872, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9895-min-1024x683.jpg" },
    ],
    image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9872-min-1024x683.jpg",
    gallery: [
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9872-min-1024x683.jpg",
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9864-min-1024x683.jpg",
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/M2A9882-min-1024x683.jpg",
    ],
    contact: { name: "Namibia Student Accommodation", phone: "+264 81 555 0103", whatsapp: "264815550103", email: "capital@namrent.na" },
    features: ["Single rooms", "Twin rooms", "Triple rooms", "Quad rooms", "Biometric access", "Cleaning services"],
    safety: "Apply only through confirmed Namibia Student Accommodation channels.",
    status: "active",
    isFeatured: true,
    popularity: 95,
  },
  {
    id: "winco-residence-student-accommodation",
    title: "Winco Residence Student Accommodation",
    description:
      "Modern Windhoek CBD student accommodation close to public transport and retail, with partially furnished twin and triple rooms.",
    price: 3074,
    deposit: 3074,
    location: "Windhoek Central",
    city: "Windhoek",
    propertyType: "Student accommodation",
    category: "Student rentals",
    bedrooms: "Twin or triple rooms",
    bathrooms: 1,
    parking: 0,
    furnished: "Partially furnished",
    utilities: "Confirm utilities with provider",
    availableFrom: "Applications open",
    pricePeriod: "per month",
    badges: ["CBD Location", "Twin Rooms", "Secure Premises"],
    roomOptions: [
      { name: "Twin Room", price: 3242, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC06987-min-1024x683.jpg" },
      { name: "Triple Room", price: 3074, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC07021-min-1024x683.jpg" },
      { name: "Student Room", price: 3242, image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC07043-min-1024x683.jpg" },
    ],
    image: "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC06987-min-1024x683.jpg",
    gallery: [
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC06987-min-1024x683.jpg",
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC07021-min-1024x683.jpg",
      "https://namstudentaccommodation.com/wp-content/uploads/2024/11/DSC07043-min-1024x683.jpg",
    ],
    contact: { name: "Namibia Student Accommodation", phone: "+264 81 555 0104", whatsapp: "264815550104", email: "winco@namrent.na" },
    features: ["Twin rooms", "Triple rooms", "Central location", "Close to transport", "Secure premises"],
    safety: "Confirm application requirements and payment details with the official provider.",
    status: "active",
    isFeatured: true,
    popularity: 93,
  },
  {
    id: "eros-airbnb-guest-suite",
    title: "Airbnb-Style Guest Suite in Eros",
    description:
      "Private furnished guest suite for short stays, visiting professionals, students on placement, and families needing temporary accommodation.",
    price: 850,
    deposit: 0,
    location: "Eros",
    city: "Windhoek",
    propertyType: "Guest suite",
    category: "Short stays",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    furnished: "Furnished",
    utilities: "Wi-Fi, water, and electricity included",
    availableFrom: "Nightly and weekly bookings",
    pricePeriod: "per night",
    badges: ["Short Stay", "Airbnb Style", "Wi-Fi Included"],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "NamRent Short Stays", phone: "+264 81 333 5510", whatsapp: "264813335510", email: "shortstays@namrent.na" },
    features: ["Self check-in", "Wi-Fi included", "Cleaning available", "Secure parking"],
    safety: "Confirm booking terms, cancellation policy, and host identity before payment.",
    status: "active",
    isFeatured: true,
    popularity: 89,
  },
  {
    id: "kleine-kuppe-holiday-apartment",
    title: "Short-Stay Apartment in Kleine Kuppe",
    description:
      "Modern furnished apartment close to shopping, medical facilities, and main routes. Suitable for weekly visits and temporary relocations.",
    price: 1200,
    deposit: 0,
    location: "Kleine Kuppe",
    city: "Windhoek",
    propertyType: "Holiday apartment",
    category: "Short stays",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    furnished: "Furnished",
    utilities: "Wi-Fi, water, electricity, and linen included",
    availableFrom: "Available for short stays",
    pricePeriod: "per night",
    badges: ["Short Stay", "Furnished", "Secure"],
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Kuppe Stay Host", phone: "+264 81 333 2214", whatsapp: "264813332214", email: "bookings@namrent.na" },
    features: ["Weekly rates", "Secure complex", "Near Grove Mall", "Linen included"],
    safety: "Use confirmed booking channels and request written booking details.",
    status: "active",
    isFeatured: false,
    popularity: 81,
  },
  {
    id: "academia-bachelor-flat",
    title: "Bachelor Flat in Academia",
    description:
      "Compact student-friendly bachelor flat close to campus routes, shops, and public transport. Ideal for one student or a young professional.",
    price: 4500,
    deposit: 4500,
    location: "Academia",
    city: "Windhoek",
    propertyType: "Bachelor flat",
    category: "Student rentals",
    bedrooms: "Bachelor",
    bathrooms: 1,
    parking: 1,
    furnished: "Semi-furnished",
    utilities: "Water included, prepaid electricity",
    availableFrom: "Available immediately",
    pricePeriod: "per month",
    badges: ["Student Friendly", "Near Campus", "Water Included"],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Martha Shikongo", phone: "+264 81 555 0192", whatsapp: "264815550192", email: "listings@namrent.na" },
    features: ["Wi-Fi ready", "Secure gate", "Public transport nearby", "Walking distance to shops"],
    safety: "Verified landlord details pending admin review.",
    status: "active",
    isFeatured: true,
    popularity: 94,
  },
  {
    id: "khomasdal-two-bedroom-flat",
    title: "2 Bedroom Flat in Khomasdal",
    description: "Neat two bedroom flat suitable for a small family or working professionals, with parking and easy access to schools.",
    price: 6500,
    deposit: 6500,
    location: "Khomasdal",
    city: "Windhoek",
    propertyType: "Flat",
    category: "Family homes",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    furnished: "Unfurnished",
    utilities: "Water excluded, prepaid electricity",
    availableFrom: "1 July 2026",
    pricePeriod: "per month",
    badges: ["Family Home", "Parking", "Long Term"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "NamRent Property Desk", phone: "+264 61 000 118", whatsapp: "26461000118", email: "family@namrent.na" },
    features: ["Covered parking", "Close to schools", "Secure boundary wall", "Quiet street"],
    safety: "View the property before making any payment.",
    status: "active",
    isFeatured: true,
    popularity: 87,
  },
  {
    id: "klein-windhoek-apartment",
    title: "Modern Apartment in Klein Windhoek",
    description: "Light-filled apartment with a practical layout, secure access, and nearby offices, restaurants, and shopping.",
    price: 9200,
    deposit: 9200,
    location: "Klein Windhoek",
    city: "Windhoek",
    propertyType: "Apartment",
    category: "Luxury rentals",
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    furnished: "Furnished",
    utilities: "Water included, electricity excluded",
    availableFrom: "15 June 2026",
    pricePeriod: "per month",
    badges: ["Furnished", "Secure", "Featured"],
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Urban Key Agents", phone: "+264 81 222 4411", whatsapp: "264812224411", email: "agents@namrent.na" },
    features: ["Biometric access", "Balcony", "Two parking bays", "Furnished lounge"],
    safety: "Agent profile marked for verification.",
    status: "active",
    isFeatured: true,
    popularity: 91,
  },
  {
    id: "pioneers-park-shared-room",
    title: "Shared Student Room in Pioneers Park",
    description: "Affordable shared accommodation with basic furniture, Wi-Fi access, and public transport nearby.",
    price: 2800,
    deposit: 2800,
    location: "Pioneers Park",
    city: "Windhoek",
    propertyType: "Shared room",
    category: "Student rentals",
    bedrooms: "Shared room",
    bathrooms: 1,
    parking: 0,
    furnished: "Furnished",
    utilities: "Water and electricity included",
    availableFrom: "Available immediately",
    pricePeriod: "per month",
    badges: ["Affordable", "Shared Accommodation", "Wi-Fi Included"],
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Student Stay Windhoek", phone: "+264 81 444 9010", whatsapp: "264814449010", email: "students@namrent.na" },
    features: ["Limited free Wi-Fi", "Cleaning support", "Shared kitchen", "Near bus route"],
    safety: "Ask for house rules and written rental terms.",
    status: "active",
    isFeatured: false,
    popularity: 78,
  },
  {
    id: "elisenheim-family-house",
    title: "3 Bedroom Family House in Elisenheim",
    description: "Spacious house with yard space, secure parking, and a peaceful residential setting for long-term tenants.",
    price: 12500,
    deposit: 12500,
    location: "Elisenheim",
    city: "Windhoek",
    propertyType: "House",
    category: "Family homes",
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    furnished: "Unfurnished",
    utilities: "Municipal services excluded",
    availableFrom: "1 August 2026",
    pricePeriod: "per month",
    badges: ["Pet Friendly", "Yard", "Family Home"],
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Family Homes Namibia", phone: "+264 81 777 3390", whatsapp: "264817773390", email: "houses@namrent.na" },
    features: ["Private yard", "Double parking", "Pet-friendly by approval", "Security alarm"],
    safety: "Confirm ownership and lease details before paying deposit.",
    status: "active",
    isFeatured: false,
    popularity: 83,
  },
  {
    id: "windhoek-central-room",
    title: "Single Room in Windhoek Central",
    description: "Central single room for a student or worker who wants quick access to town, transport, and services.",
    price: 3200,
    deposit: 3200,
    location: "Windhoek Central",
    city: "Windhoek",
    propertyType: "Room",
    category: "Affordable rentals",
    bedrooms: "Single room",
    bathrooms: 1,
    parking: 0,
    furnished: "Furnished",
    utilities: "Water included, electricity shared",
    availableFrom: "20 June 2026",
    pricePeriod: "per month",
    badges: ["Central", "Affordable", "Furnished"],
    image: "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618221118493-9cfa1a1c00da?auto=format&fit=crop&w=1200&q=80",
    ],
    contact: { name: "Central Rentals Desk", phone: "+264 81 999 7020", whatsapp: "264819997020", email: "central@namrent.na" },
    features: ["Close to town", "Shared bathroom", "Furnished room", "Public transport nearby"],
    safety: "Meet the advertiser at the property address.",
    status: "active",
    isFeatured: false,
    popularity: 75,
  },
];
